# .github/workflows/hello-world.yml
#The name of the workflow, will be displayed on the Github actions page
name: Continuous Deployment
# when to execute it, similar to Azure DevOps trigger keyword
#testing dev branch
on: 
  pull_request:
    types: [closed]

# list of jobs to execute
jobs:
  terraform:
    runs-on: ubuntu-latest
    env:
        ARM_CLIENT_ID: ${{ secrets.CLIENTID }}
        ARM_CLIENT_SECRET: ${{ secrets.CLIENTSECRET }}
        ARM_SUBSCRIPTION_ID: ${{ secrets.SUBSCRIPTIONID }}
        ARM_TENANT_ID: ${{ secrets.TENANTID }}
        SOURCE_DIR: ""
        BRANCH: ""
    steps:
        - name: Set SourceDir based on  prod branch
          run: echo '::set-env name=SOURCE_DIR::${{ github.workspace }}/infrastructure/dev'

        - name: Checkout
          uses: actions/checkout@v2
    
        - name: Setup Terraform
          uses: hashicorp/setup-terraform@v1.1.0

        - name: echo branchname
          run: |
            raw=${GITHUB_HEAD_REF##*/}
            branch=$(echo ${raw/origin\/} | rev | cut -d'/' -f 1 | rev | cut -c 1-10)
            echo ::set-env name=BRANCH::$branch        

        - name: Terraform Init
          run: terraform init $SOURCE_DIR

        - name: Terraform Workspace select
          run: terraform workspace select $BRANCH $SOURCE_DIR || true

        - name: Terraform Destroy
          if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true
          run: terraform destroy -auto-approve $SOURCE_DIR 
